import React from "react";
import { StyleSheet } from "react-native"; 
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
export const chartColors = {bnb:'#F3BA2F', btc:'#F7931A', eth:'#00aaa1', icicb:'#e6be75', ltc:'#236bff', usdt:'#36f32d'};
export const Colors = {
	Primary: "#e6be75",
	DarkPrimary:"#4d4840",
	Dark: "#010101",
	Light: "#ffffff", 
}
export const w = (w) => wp(w + '%')
export const h = (h) => hp(h + '%')

const styles = StyleSheet.create({
	container: { 
		flex: 1 
	},
	textcenter: {textAlign: 'center'},
	textleft: {textAlign: 'left'},
	textright: {textAlign: 'right'},

	t1: 	{ fontSize: hp('5%') },
	t2: 	{ fontSize: hp('3.5%') },
	t3: 	{ fontSize: hp('2.5%') },
	t: 		{ fontSize: hp('2%') },
	t0: 	{ fontSize: hp('1.5%') },

	underline:	{textDecorationLine:'underline'},

	mlauto: {marginLeft:		'auto'},
	mrauto: {marginRight:		'auto'},
	mbauto: {marginBottom:		'auto'},
	mtauto: {marginTop:			'auto'},

	m1:  	{ margin: 			hp('1%') },
	m2:  	{ margin: 			hp('2%') },
	m3:  	{ margin: 			hp('3%') },
	m4:  	{ margin: 			hp('4%') },
	m5:  	{ margin: 			hp('5%') },
	ml1: 	{ marginLeft: 		wp('1%') },
	ml2: 	{ marginLeft: 		wp('2%') },
	ml3: 	{ marginLeft: 		wp('3%') },
	ml4: 	{ marginLeft: 		wp('4%') },
	ml5: 	{ marginLeft: 		wp('5%') },
	mr1: 	{ marginRight: 		wp('1%') },
	mr2: 	{ marginRight: 		wp('2%') },
	mr3: 	{ marginRight: 		wp('3%') },
	mr4: 	{ marginRight: 		wp('4%') },
	mr5: 	{ marginRight: 		wp('5%') },
	mt1: 	{ marginTop: 		hp('1%') },
	mt2: 	{ marginTop: 		hp('2%') },
	mt3: 	{ marginTop: 		hp('3%') },
	mt4: 	{ marginTop: 		hp('4%') },
	mt5: 	{ marginTop: 		hp('5%') },
	mb1: 	{ marginBottom: 	hp('1%') },
	mb2: 	{ marginBottom: 	hp('2%') },
	mb3: 	{ marginBottom: 	hp('3%') },
	mb4: 	{ marginBottom: 	hp('4%') },
	mb5: 	{ marginBottom: 	hp('5%') },

	p1:  	{ padding: 			hp('1%') },
	p2:  	{ padding: 			hp('2%') },
	p3:  	{ padding: 			hp('3%') },
	p4:  	{ padding: 			hp('4%') },
	p5:  	{ padding: 			hp('5%') },
	pl1: 	{ paddingLeft: 		wp('1%') },
	pl2: 	{ paddingLeft: 		wp('2%') },
	pl3: 	{ paddingLeft: 		wp('3%') },
	pl4: 	{ paddingLeft: 		wp('4%') },
	pl5: 	{ paddingLeft: 		wp('5%') },
	pr1: 	{ paddingRight: 	wp('1%') },
	pr2: 	{ paddingRight: 	wp('2%') },
	pr3: 	{ paddingRight: 	wp('3%') },
	pr4: 	{ paddingRight: 	wp('4%') },
	pr5: 	{ paddingRight: 	wp('5%') },
	pt1: 	{ paddingTop: 		hp('1%') },
	pt2: 	{ paddingTop: 		hp('2%') },
	pt3: 	{ paddingTop: 		hp('3%') },
	pt4: 	{ paddingTop: 		hp('4%') },
	pt5: 	{ paddingTop: 		hp('5%') },
	pb1: 	{ paddingBottom: 	hp('1%') },
	pb2: 	{ paddingBottom: 	hp('2%') },
	pb3: 	{ paddingBottom: 	hp('3%') },
	pb4: 	{ paddingBottom: 	hp('4%') },
	pb5: 	{ paddingBottom: 	hp('5%') },

	h: 		{ height : 			hp('6%') },

	w100:	{width:				'100%'},
	w90:	{width:				'90%'},
	w80:	{width:				'80%'},
	w70:	{width:				'70%'},
	w60:	{width:				'60%'},
	w50:	{width:				'50%'},
	w40:	{width:				'40%'},
	w30:	{width:				'30%'},
	w20:	{width:				'20%'},
	w10:	{width:				'10%'},
	wauto:	{width:				'auto'},

	h10: 	{height:			'10%'},
	h20: 	{height:			'20%'},
	h30: 	{height:			'30%'},
	h40: 	{height:			'40%'},
	h50: 	{height:			'50%'},
	h60: 	{height:			'60%'},
	h70: 	{height:			'70%'},
	h80: 	{height:			'80%'},
	h90: 	{height:			'90%'},
	h100: 	{height:			'100%'},
	hauto: 	{height:			'auto'},

	left0:		{left:				0},
	right0:		{right:				0},
	top0:		{top:				0},
	bottom0:	{bottom:			0},

	backgroundwhite:	{backgroundColor:	'white'},
	
	whitecolor:	{color:			'white'},
	greycolor:	{color:			'grey'},
	blackcolor:	{color:			'black'},
	greencolor:	{color:			'green'},
	redcolor:	{color:			'red'},
	yellowcolor:	{color:			'yellow'},
	primarycolor:	{color:			Colors.Primary},
	darkprimarycolor:	{color:			Colors.DarkPrimary},
	darkcolor:	{color:			Colors.Dark},
	lightcolor:	{color:			Colors.Light},

	flex:			{display:		"flex"},
	hide:			{display:		"none"},
	alignitemcenter:	{alignItems:	"center"},
	alignitemend:		{alignItems:	"flex-end"},
	alignitemstart:		{alignItems:	"flex-start"},

	justifycenter:		{justifyContent:	"center"},
	justifystart:		{justifyContent:	"flex-start"},
	justifyend:			{justifyContent:	"flex-end"},
	justifybetween:		{justifyContent:	"space-between"},
	justifyaround:		{justifyContent:	"space-around"},

	flexdirectionrow:		{flexDirection:		"row"},
	flexdirectioncolumn:	{flexDirection:		"column"},
	flexdirectioncolumnreverse:	{flexDirection:		"column-reverse"},
	flexdirectionrowreverse:	{flexDirection:		"row-reverse"},


	flexwrap:			{flexWrap:	'wrap'},
	flexnowrap:			{flexWrap:	'nowrap'},

	flex1:		{flex:	1},
	flex2:		{flex:	2},
	flex3:		{flex:	3},
	flex4:		{flex:	4},
	flex5:		{flex:	5},
	flex6:		{flex:	6},
	flex7:		{flex:	7},
	flex8:		{flex:	8},
	flex9:		{flex:	9},
	flex10:		{flex:	10},
	flex11:		{flex:	11},
	flex12:		{flex:	11},

	relative:	{position: 'relative'},
	absolute:	{position: 'absolute'},

	borderradius1:	{borderRadius:	wp('0.2%')},
	borderradius2:	{borderRadius:	wp('0.4%')},
	borderradius3:	{borderRadius:	wp('0.5%')},
	borderradius4:	{borderRadius:	wp('0.6%')},
	borderradius5:	{borderRadius:	wp('0.7%')},
	borderradius6:	{borderRadius:	wp('0.9%')},
	borderradius7:	{borderRadius:	wp('1%')},
	borderradius8:	{borderRadius:	wp('1.2%')},
	borderradius9:	{borderRadius:	wp('1.4%')},
	borderradius10:	{borderRadius:	wp('1.5%')},
	borderradius15:	{borderRadius:	wp('2.5%')},
	borderradius20:	{borderRadius:	wp('5%')},

	borderwidth1:	{borderWidth:	0.1},
	borderwidth2:	{borderWidth:	0.2},
	borderwidth3:	{borderWidth:	0.3},
	borderwidth4:	{borderWidth:	0.4},
	borderwidth5:	{borderWidth:	0.5},
	borderwidth6:	{borderWidth:	0.6},
	borderwidth7:	{borderWidth:	0.7},
	borderwidth8:	{borderWidth:	0.8},
	borderwidth9:	{borderWidth:	0.9},
	borderwidth10:	{borderWidth:	1},
	borderwidth20:	{borderWidth:	2},
	
	borderstylesolid:	{borderStyle:	'solid'},
	borderstyledotted:	{borderStyle:	'dotted'},
	borderstyledashed:	{borderStyle:	'dashed'}
	
});
  
export default styles